# Generated by Django 5.1.4 on 2026-05-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
