# Generated by Django 5.1.4 on 2026-05-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0002_alter_uploadedimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='predicted_text',
            field=models.TextField(blank=True),
        ),
    ]
