# Generated by Django 5.1.4 on 2026-05-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0003_uploadedimage_predicted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='ocr_engine',
            field=models.CharField(choices=[('local', 'Local Tesseract OCR'), ('api', 'API Key Model')], default='local', max_length=20),
        ),
    ]
