# Generated by Django 5.1.4 on 2026-05-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0004_uploadedimage_ocr_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='raw_ocr_text',
            field=models.TextField(blank=True),
        ),
    ]
