# Generated by Django 5.1.4 on 2026-05-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0005_uploadedimage_raw_ocr_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='ocr_engine',
            field=models.CharField(choices=[('smart', 'Smart Hybrid OCR (Recommended)'), ('local', 'Local Tesseract OCR'), ('ai_local', 'Local AI Handwriting Model'), ('api', 'API Key Model')], default='smart', max_length=20),
        ),
    ]
