# Generated by Django 5.1.4 on 2026-05-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0008_uploadedimage_prediction_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='added_to_training_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='correction_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='user_corrected_text',
            field=models.TextField(blank=True),
        ),
    ]
