# Generated by Django 5.1.4 on 2026-06-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0010_uploadedimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='image_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='prediction_source',
            field=models.CharField(blank=True, choices=[('gemini', 'Gemini'), ('api', 'API OCR'), ('local', 'Local OCR'), ('local_ai', 'Local AI OCR'), ('memory', 'Saved Correction'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
